// constants/sidebar.ts
import {
    Home,
    BookOpen,
    Calendar,
    BarChart2,
    MessageCircle,
    CreditCard,
    FileText,
    LogOut,
    Users,
    User,
    Plus,
    ClipboardList,
    Send,
    Settings,
    Layout,
    GraduationCap,
    UserPlus,
    UserCheck,
    File,
    Award,
    Newspaper,
    Scroll,
    AwardIcon,
    DollarSign,
    ChartColumn,
    Settings2,
    LayoutDashboard,
    Briefcase,
    MessageSquare,
    House,
    CalendarClock,
    Shield,
} from "lucide-react";
import { SidebarItem } from "../types/sidebar";
import { Permission } from "../enums/permissions";

export const PARENT_MENU_ITEMS: SidebarItem[] = [
    {
        label: "Analytics",
        description: "Performance Insights",
        tab: "analytics",
        href: "/frontend/pages/parent?tab=analytics",
        icon: ChartColumn,
        permission: Permission.ANALYTICS,
    },
    {
        label: "Home",
        tab: "dashboard",
        href: "/frontend/pages/parent?tab=dashboard",
        icon: House,
        permission: Permission.HOME,
    },
    {
        label: "Profile",
        tab: "profile",
        href: "/frontend/pages/parent?tab=profile",
        icon: User,
        permission: Permission.PROFILE,
    },
    {
        label: "Homework",
        tab: "homework",
        href: "/frontend/pages/parent?tab=homework",
        icon: BookOpen,
        permission: Permission.HOMEWORK,
    },
    {
        label: "Attendance",
        tab: "attendance",
        href: "/frontend/pages/parent?tab=attendance",
        icon: Calendar,
        permission: Permission.ATTENDANCE,
    },
    {
        label: "Marks",
        tab: "marks",
        href: "/frontend/pages/parent?tab=marks",
        icon: Award,
        permission: Permission.MARKS,
    },
    {
        label: "Exams & Syllabus",
        tab: "exams",
        href: "/frontend/pages/parent?tab=exams",
        icon: ClipboardList,
        permission: Permission.EXAMS,
    },
    {
        label: "Chat",
        tab: "chat",
        href: "/frontend/pages/parent?tab=chat",
        icon: MessageCircle,
        permission: Permission.CHAT,
    },
    {
        label: "Workshops",
        tab: "workshops",
        href: "/frontend/pages/parent?tab=workshops",
        icon: Briefcase,
        permission: Permission.WORKSHOPS,
    },
    {
        label: "Certificates",
        tab: "certificates",
        href: "/frontend/pages/parent?tab=certificates",
        icon: FileText,
        permission: Permission.CERTIFICATES,
    },
    {
        label: "Fees",
        tab: "fees",
        href: "/frontend/pages/parent?tab=fees",
        icon: CreditCard,
        permission: Permission.FEES,
    },
    {
        label: "Leave Application",
        tab: "leave",
        href: "/frontend/pages/parent?tab=leave",
        icon: CalendarClock,
        permission: Permission.STUDENT_LEAVE,
    },
    {
        label: "Settings",
        tab: "settings",
        href: "/frontend/pages/parent?tab=settings",
        icon: Settings,
        permission: Permission.SETTINGS,
    },
    {
        label: "Logout",
        icon: LogOut,
        action: "logout",
    },
];



export const SCHOOLADMIN_MENU_ITEMS: SidebarItem[] = [
    {
        label: "Dashboard",
        tab: "dashboard",
        href: "/frontend/pages/schooladmin?tab=dashboard",
        icon: Layout,
        permission: Permission.DASHBOARD,
    },
    // {
    //     label: "Classes",
    //     tab: "classes",
    //     href: "/frontend/pages/schooladmin?tab=classes",
    //     icon: GraduationCap,
    //     permission: Permission.CLASSES,
    // },
    // {
    //     label: "Students",
    //     tab: "students",
    //     href: "/frontend/pages/schooladmin?tab=students",
    //     icon: Users,
    //     permission: Permission.STUDENTS,
    // },
    {
        label: "Add User",
        tab: "add-user",
        href: "/frontend/pages/schooladmin?tab=add-user",
        icon: UserPlus,
        permission: Permission.NEW_USER,
    },
    {
        label: "Principal",
        tab: "principal",
        href: "/frontend/pages/schooladmin?tab=principal",
        icon: Shield,
        permission: Permission.NEW_USER,
    },
    {
        label: "Student Details",
        tab: "student-details",
        href: "/frontend/pages/schooladmin?tab=student-details",
        icon: User,
        permission: Permission.STUDENT_DETAILS,
    },
    // {
    //     label: "Teachers",
    //     tab: "teachers",
    //     href: "/frontend/pages/schooladmin?tab=teachers",
    //     icon: UserCheck,
    //     permission: Permission.TEACHERS,
    // },
    // {
    //     label: "Teacher Leaves",
    //     tab: "teacher-leaves",
    //     href: "/frontend/pages/schooladmin?tab=teacher-leaves",
    //     icon: FileText,
    //     permission: Permission.TEACHER_LEAVES,
    // },
    // {
    //     label: "Teacher Audit",
    //     tab: "teacher-audit",
    //     href: "/frontend/pages/schooladmin?tab=teacher-audit",
    //     icon: Award,
    //     permission: Permission.TEACHER_AUDIT,
    // },
    // {
    //     label: "Workshops & Events",
    //     tab: "workshops",
    //     href: "/frontend/pages/schooladmin?tab=workshops",
    //     icon: Calendar,
    //     permission: Permission.WORKSHOPS,
    // },
    {
        label: "Newsfeed",
        tab: "newsfeed",
        href: "/frontend/pages/schooladmin?tab=newsfeed",
        icon: Newspaper,
        permission: Permission.NEWSFEED,
    }, {
        label: "Circulars",
        tab: "circulars",
        href: "/frontend/pages/schooladmin?tab=circulars",
        icon: Scroll,
        permission: Permission.CIRCULARS,
    },
    // {
    //     label: "Certificate Request",
    //     tab: "certificates",
    //     href: "/frontend/pages/schooladmin?tab=certificates",
    //     icon: AwardIcon,
    //     permission: Permission.CERTIFICATES,
    // },
    {
        label: "Fees",
        tab: "fees",
        href: "/frontend/pages/schooladmin?tab=fees",
        icon: DollarSign,
        permission: Permission.FEES,
    },
    // {
    //     label: "Exams",
    //     tab: "exams",
    //     href: "/frontend/pages/schooladmin?tab=exams",
    //     icon: ClipboardList,
    //     permission: Permission.EXAMS,
    // },
    {
        label: "Analysis",
        tab: "analysis",
        href: "/frontend/pages/schooladmin?tab=analysis",
        icon: ChartColumn,
        permission: Permission.ANALYSIS,
    },
    {
        label: "Settings",
        tab: "settings",
        href: "/frontend/pages/schooladmin?tab=settings",
        icon: Settings,
        permission: Permission.SETTINGS,
    },
    {
        label: "Logout",
        icon: LogOut,
        action: "logout",
    },
];

export const SCHOOLADMIN_TAB_TITLES: Record<string, string> = {
    dashboard: "Dashboard",
    students: "Students",
    teachers: "Teachers",
    classes: "Classes",
    "teacher-leaves": "Teacher Leaves",
    "tc-approvals": "TC Approvals",
    payments: "Payments",
    workshops: "Workshops & Events",
    newsfeed: "Newsfeed",
    exams: "Exams",
    analysis: "Analysis",
    "student-details": "Student Details",
    "add-user": "Add User",
    principal: "Principal",
    "teacher-audit": "Teacher Audit",
    circulars: "Circulars",
    certificates: "Certificate Requests",
    fees: "Fees",
    settings: "Settings",
};

export const TEACHER_MENU_ITEMS: SidebarItem[] = [
    {
        label: "Dashboard",
        tab: "dashboard",
        href: "/frontend/pages/teacher?tab=dashboard",
        icon: LayoutDashboard,
        permission: Permission.DASHBOARD,
    },
    {
        label: "Classes",
        tab: "classes",
        href: "/frontend/pages/teacher?tab=classes",
        icon: GraduationCap,
        permission: Permission.CLASSES,
    },
    {
        label: "Homework",
        tab: "homework",
        href: "/frontend/pages/teacher?tab=homework",
        icon: BookOpen,
        permission: Permission.HOMEWORK,
    },
    {
        label: "Marks",
        tab: "marks",
        href: "/frontend/pages/teacher?tab=marks",
        icon: Award,
        permission: Permission.MARKS,
    },
    {
        label: "Attendance",
        tab: "attendance",
        href: "/frontend/pages/teacher?tab=attendance",
        icon: Calendar,
        permission: Permission.ATTENDANCE,
    },
    {
        label: "Exams & Syllabus",
        tab: "exams",
        href: "/frontend/pages/teacher?tab=exams",
        icon: FileText,
        permission: Permission.EXAMS,
    },
    {
        label: "Worksops & Events",
        tab: "workshops",
        href: "/frontend/pages/teacher?tab=workshops",
        icon: Briefcase,
        permission: Permission.WORKSHOPS,
    }, {
        label: "Newsfeed",
        tab: "newsfeed",
        href: "/frontend/pages/teacher?tab=newsfeed",
        icon: Newspaper,
        permission: Permission.NEWSFEED,
    }, {
        label: "Parent Chat",
        tab: "chat",
        href: "/frontend/pages/teacher?tab=chat",
        icon: MessageSquare,
        permission: Permission.CHAT,
    },
    {
        label: "Leave",
        tab: "leaves",
        href: "/frontend/pages/teacher?tab=leaves",
        icon: FileText,
        permission: Permission.LEAVES,
    },
    {
        label: "Profile",
        tab: "profile",
        href: "/frontend/pages/teacher?tab=profile",
        icon: User,
        permission: Permission.PROFILE,
    },
    {
        label: "Settings",
        tab: "settings",
        href: "/frontend/pages/teacher?tab=settings",
        icon: Settings,
        permission: Permission.SETTINGS,
    },
    {
        label: "Sign Out",
        action: "logout",
        icon: LogOut,
    },
];



export const SUPERADMIN_SIDEBAR_ITEMS: SidebarItem[] = [
    {
        label: "Dashboard",
        href: "/frontend/pages/superadmin",
        tab: "dashboard",
        icon: Home,
        permission: Permission.DASHBOARD,
    },
    {
        label: "Add School",
        mobileLabel: "Add",
        href: "/frontend/pages/superadmin?tab=addschool",
        tab: "addschool",
        icon: Plus,
        permission: Permission.ADD_SCHOOL,
    },
    {
        label: "Schools",
        href: "/frontend/pages/superadmin?tab=schools",
        tab: "schools",
        icon: Users,
        permission: Permission.SCHOOLS,
    },
    {
        label: "Fees Transactions",
        mobileLabel: "Fees",
        href: "/frontend/pages/superadmin?tab=transactions",
        tab: "transactions",
        icon: CreditCard,
        permission: Permission.FEES_TRANSACTIONS,
    },
    {
        label: "Sign Out",
        action: "logout",
        icon: LogOut,
    },
];



// Principal: same layout as School Admin, with "Add HOD" instead of "Principal" tab
export const PRINCIPAL_MENU_ITEMS: SidebarItem[] = [
    { label: "Dashboard", tab: "dashboard", href: "/frontend/pages/principle?tab=dashboard", icon: Layout, permission: Permission.DASHBOARD },
    { label: "Classes", tab: "classes", href: "/frontend/pages/principle?tab=classes", icon: GraduationCap, permission: Permission.CLASSES },
    { label: "Students", tab: "students", href: "/frontend/pages/principle?tab=students", icon: Users, permission: Permission.STUDENTS },
    { label: "Add User", tab: "add-user", href: "/frontend/pages/principle?tab=add-user", icon: UserPlus, permission: Permission.NEW_USER },
    { label: "Add HOD", tab: "add-hod", href: "/frontend/pages/principle?tab=add-hod", icon: Shield, permission: Permission.ADD_HOD },
    { label: "Student Details", tab: "student-details", href: "/frontend/pages/principle?tab=student-details", icon: User, permission: Permission.STUDENT_DETAILS },
    { label: "Teachers", tab: "teachers", href: "/frontend/pages/principle?tab=teachers", icon: UserCheck, permission: Permission.TEACHERS },
    { label: "Teacher Leaves", tab: "teacher-leaves", href: "/frontend/pages/principle?tab=teacher-leaves", icon: FileText, permission: Permission.TEACHER_LEAVES },
    { label: "Teacher Audit", tab: "teacher-audit", href: "/frontend/pages/principle?tab=teacher-audit", icon: Award, permission: Permission.TEACHER_AUDIT },
    { label: "Workshops & Events", tab: "workshops", href: "/frontend/pages/principle?tab=workshops", icon: Calendar, permission: Permission.WORKSHOPS },
    { label: "Newsfeed", tab: "newsfeed", href: "/frontend/pages/principle?tab=newsfeed", icon: Newspaper, permission: Permission.NEWSFEED },
    { label: "Circulars", tab: "circulars", href: "/frontend/pages/principle?tab=circulars", icon: Scroll, permission: Permission.CIRCULARS },
    { label: "Certificate Request", tab: "certificates", href: "/frontend/pages/principle?tab=certificates", icon: AwardIcon, permission: Permission.CERTIFICATES },
    { label: "Fees", tab: "fees", href: "/frontend/pages/principle?tab=fees", icon: DollarSign, permission: Permission.FEES },
    { label: "Exams", tab: "exams", href: "/frontend/pages/principle?tab=exams", icon: ClipboardList, permission: Permission.EXAMS },
    { label: "Analysis", tab: "analysis", href: "/frontend/pages/principle?tab=analysis", icon: ChartColumn, permission: Permission.ANALYSIS },
    { label: "Settings", tab: "settings", href: "/frontend/pages/principle?tab=settings", icon: Settings, permission: Permission.SETTINGS },
    { label: "Logout", icon: LogOut, action: "logout" },
];

export const PRINCIPAL_TAB_TITLES: Record<string, string> = {
    dashboard: "Dashboard",
    students: "Students",
    teachers: "Teachers",
    classes: "Classes",
    "teacher-leaves": "Teacher Leaves",
    "add-user": "Add User",
    "add-hod": "Add HOD",
    "student-details": "Student Details",
    "teacher-audit": "Teacher Audit",
    workshops: "Workshops & Events",
    newsfeed: "Newsfeed",
    circulars: "Circulars",
    certificates: "Certificate Requests",
    fees: "Fees",
    exams: "Exams",
    analysis: "Analysis",
    settings: "Settings",
};



export const HOD_MENU_ITEMS: SidebarItem[] = [
    {
        label: "Dashboard",
        tab: "dashboard",
        href: "/frontend/pages/hod?tab=dashboard",
        icon: LayoutDashboard,
        permission: Permission.DASHBOARD,
    },
    // {
    //     label: "Classes",
    //     tab: "classes",
    //     href: "/frontend/pages/hod?tab=classes",
    //     icon: GraduationCap,
    //     permission: Permission.CLASSES,
    // },
    {
        label: "Teacher Attendance",
        tab: "teacherAttendence",
        href: "/frontend/pages/hod?tab=teacherAttendence",
        icon: Calendar,
        permission: Permission.TEACHER_ATTENDANCE,
    },
    {
        label: "Student Attendance",
        tab: "studentAttendence",
        href: "/frontend/pages/hod?tab=studentAttendence",
        icon: Calendar,
        permission: Permission.STUDENT_ATTENDANCE,
    },
    {
        label: "Add User",
        tab: "addUser",
        href: "/frontend/pages/hod?tab=addUser",
        icon: UserPlus,
        permission: Permission.NEW_USER,
    },
    // {
    //     label: "Add Students",
    //     tab: "addStudents",
    //     href: "/frontend/pages/hod?tab=addStudents",
    //     icon: UserPlus,
    //     permission: Permission.ADD_STUDENTS,
    // },
    {
        label: "Teacher Audit",
        tab: "teacherAudit",
        href: "/frontend/pages/hod?tab=teacherAudit",
        icon: Award,
        permission: Permission.TEACHER_AUDIT,
    },
    {
        label: "Circulars",
        tab: "circular",
        href: "/frontend/pages/hod?tab=circular",
        icon: Scroll,
        permission: Permission.CIRCULARS,
    },
    {
        label: "Exam Syllabus",
        tab: "examAndSyllabus",
        href: "/frontend/pages/hod?tab=examAndSyllabus",
        icon: FileText,
        permission: Permission.EXAM_SYLLABUS,
    },
    {
        label: "Room Allocation",
        tab: "roomAllocation",
        href: "/frontend/pages/hod?tab=roomAllocation",
        icon: Layout,
        permission: Permission.ROOM_ALLOCATION,
    },
    {
        label: "News Feed",
        tab: "newsFeed",
        href: "/frontend/pages/hod?tab=newsFeed",
        icon: Newspaper,
        permission: Permission.NEWSFEED,
    },
    {
        label: "Workshops",
        tab: "workShops",
        href: "/frontend/pages/hod?tab=workShops",
        icon: Briefcase,
        permission: Permission.WORKSHOPS,
    },
    {
        label: "Time Table",
        tab: "timeTable",
        href: "/frontend/pages/hod?tab=timeTable",
        icon: CalendarClock,
        permission: Permission.TIME_TABLE,
    },
    {
        label: "Library",
        tab: "library",
        href: "/frontend/pages/hod?tab=library",
        icon: BookOpen,
        permission: Permission.LIBRARY,
    },
    {
        label: "Assignments",
        tab: "assignments",
        href: "/frontend/pages/hod?tab=assignments",
        icon: ClipboardList,
        permission: Permission.ASSIGNMENTS,
    },
    {
        label: "Marks",
        tab: "marks",
        href: "/frontend/pages/hod?tab=marks",
        icon: Award,
        permission: Permission.MARKS,
    },
    {
        label: "Analysis",
        tab: "analysis",
        href: "/frontend/pages/hod?tab=analysis",
        icon: ChartColumn,
        permission: Permission.ANALYSIS,
    },
    {
        label: "Settings",
        tab: "settings",
        href: "/frontend/pages/hod?tab=settings",
        icon: Settings,
        permission: Permission.SETTINGS,
    },
    {
        label: "Logout",
        icon: LogOut,
        action: "logout",
    },
];
