// constants/permissions.ts
export enum Permission {
  DASHBOARD = "DASHBOARD",
  HOMEWORK = "HOMEWORK",
  ATTENDANCE = "ATTENDANCE",
  MARKS = "MARKS",
  CHAT = "CHAT",
  FEES = "FEES",
  CERTIFICATES = "CERTIFICATES",

  // School Admin
  CLASSES = "CLASSES",
  STUDENTS = "STUDENTS",
  TEACHERS = "TEACHERS",
  TEACHER_LEAVES = "TEACHER_LEAVES",
  WORKSHOPS = "WORKSHOPS",
  NEWSFEED = "NEWSFEED",
  TC_APPROVALS = "TC_APPROVALS",
  PAYMENTS = "PAYMENTS",
  STUDENT_DETAILS = "STUDENT_DETAILS",
  ANALYSIS = "ANALYSIS",
  EXAMS = "EXAMS",
  NEW_USER = "NEW_USER",
  TEACHER_AUDIT = "TEACHER_AUDIT",

  // Super Admin
  ADD_SCHOOL = "ADD_SCHOOL",
  SCHOOLS = "SCHOOLS",
  FEES_TRANSACTIONS = "FEES_TRANSACTIONS",
  CIRCULARS = "CIRCULARS",
  SETTINGS = "SETTINGS",
  PROFILE = "PROFILE",
  HOME = "HOME",
  STUDENT_LEAVE = "STUDENT_LEAVE",
  LEAVES="LEAVES",
  ANALYTICS = "ANALYTICS",

  // Principal
  ADD_HOD = "ADD_HOD",
  BUS_BOOKING = "BUS_BOOKING",
  EXAM_SYLLABUS = "EXAM_SYLLABUS",
  HOD_LEAVES = "HOD_LEAVES",
  HOSTEL_BOOKING = "HOSTEL_BOOKING",
  LIBRARY = "LIBRARY",
  ROOM_ALLOCATION = "ROOM_ALLOCATION",
  TEACHER_ATTENDANCE = "TEACHER_ATTENDANCE",
  TIME_TABLE = "TIME_TABLE",

  // HOD
  STUDENT_ATTENDANCE = "STUDENT_ATTENDANCE",
  ADD_STUDENTS = "ADD_STUDENTS",
  ASSIGNMENTS = "ASSIGNMENTS",
}
